# Site settings
title: FreeCodeCamp Madrid Website
email: freecodecampmadrid@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fccmadrid.github.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: :compressed
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate